version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://healthtrack:Admin@123@db:3306/healthtrack_db
      SECRET_KEY: ${SECRET_KEY:-your_secure_secret_key}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your_secure_jwt_key}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app:cached
    networks:
      - healthtrack-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db:
    image: mysql:8.0-debian
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: healthtrack_db
      MYSQL_USER: healthtrack
      MYSQL_PASSWORD: Admin@123
      MYSQL_ROOT_PASSWORD: Root@123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - healthtrack-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uhealthtrack -phealthtrack_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  healthtrack-network:
    driver: bridge
