version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://healthtrack:healthtrack_password@db:3306/healthtrack_db
      - SECRET_KEY=your_secure_secret_key
      - JWT_SECRET_KEY=your_secure_jwt_key
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    networks:
      - healthtrack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db:
    image: mysql:8.0-debian
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=healthtrack_db
      - MYSQL_USER=healthtrack
      - MYSQL_PASSWORD=healthtrack_password
      - MYSQL_ROOT_PASSWORD=root_secure_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - healthtrack-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "healthtrack", "-phealthtrack_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  healthtrack-network:
    driver: bridge